# obtained from
# - https://youtu.be/hPfk0qd4xEY?t=239
# - https://technotim.com/posts/keepalived-ha-loadbalancer/#configuration
# - https://keepalived.readthedocs.io/en/latest/configuration_synopsis.html#vrrp-instance-definitions-synopsis
vrrp_instance VI_1 {
  state MASTER                    # primary is 'MASTER', secondary is 'BACKUP'
  interface eth0
  virtual_router_id 55
  priority 150                    # higher number is higher priority
  advert_int 1                    # advertisement interval in seconds
  unicast_src_ip 192.168.1.247    # IP of the current machine. Proxmox machine
  unicast_peer {                  # IP of the secondary machine. Raspberry Pi
    192.168.1.253
  }

  authentication {
    auth_type PASS
    auth_pass Vc#FIxFO17dMN^EtN^mUBs3u8y29l3
  }

  virtual_ipaddress {
    192.168.1.100/24              # IP shared by Proxmox and Raspberry Pi. Both machines will be using this IP, if main goes down, the backup machine takes over
  }
}
